### ISSUE TITLE
Functionality with fieldsets in forms

### ISSUE THREAD

**Issue by rolandhediger** [bramstroker/zf2-form#30]
The validation does not seem to work client side when the form has a fieldset element added to it. The server side validation seems to work however, which would indicate that the code is correct. I am not sure if there is something else I need to add or if this module simply does not process the fieldsets into jquery validation.

**Comment by bramstroker** [comment]
This module supports fieldsets. Could you supply the code related to the form/fieldset setup which causes problems?

**Comment by rolandhediger** [comment]
Sure thing, its quite a bit of code. I would like to give a fair warning that, while I am an experienced programmer and user of mvc frameworks, I am a little new to Zend Framework, so it could be something obvious that I just can't see. So I apologise if this ends up wasting your time. I would appreciate your help though.

The Form code:
lass ItemForm extends Form{

    public function __construct($hydrator){
        parent::__construct('itemForm');

        $this->setHydrator($hydrator);
        $this->setObject(new Item());
      $itemFieldSet = new ItemFieldSet($hydrator);
        $itemFieldSet->setUseAsBaseFieldset(true);
        $this->add($itemFieldSet);



        $this->add(array(
            'name' => 'submit',
            'type' => 'Submit',
            'attributes' => array(
                'value' => 'Save',
                'class'=> 'btn btn-default'
            ),
        ));
    }
}
Fieldsets:

  class ItemFieldSet extends Fieldset implements InputFilterProviderInterface{



    public function __construct($hydrator){

    parent::__construct('item');

        $this->setHydrator($hydrator);
        $this->setObject(new Item());
        $this->setAttributes(array('class'=>'form-horizontal'));

        $this->add(array(
            'name'=>'id',
            'type'=>'Hidden'
        ));

        $this->add(array(
            'name'=>'container',
            'type'=>'Hidden'
        ));

        $this->add(array(
            'name' => 'name',
            'type' => 'Text',
            'options' => array(
                'label' => 'Name',
            ),
        ));
        $this->add(array(
            'name' => 'description',
            'type' => 'textarea',
            'options' => array(
                'label' => 'Description',

            ),
            'attributes'=> array( 'cols' => '10',
                'rows' => '10')
        ));

        $attributeFieldSet = new AttributeFieldSet($hydrator);
        $this->add(array(
            'type'    => 'Zend\Form\Element\Collection',
            'name'    => 'attributes',
            'options' => array(
                'count'           => 2,
                'target_element' => $attributeFieldSet)));

        $file = new File('pictures');
        $file->setLabel('Upload Pictures')
            ->setAttribute('id', 'image-file')
            ->setAttribute('multiple', true);   // That's it
        $this->add($file);


    }
    /**
     * Should return an array specification compatible with
     * {@link Zend\InputFilter\Factory::createInputFilter()}.
     *
     * @return array
     */
    public function getInputFilterSpecification()
    {
          $result = array();
        $name = array(
            'name' => 'name',
            'required' => true,
            'filters' => array(
                array('name' => 'StripTags'),
                array('name' => 'StringTrim'),
            ),
            'validators' => array(
                array(
                    'name' => 'StringLength',
                    'options' => array(
                        'encoding' => 'UTF-8',
                        'min' => 1,
                        'max' => 100,
                    ),
                ),
            ),
        );
        $description = array(
            'name' => 'description',
            'required' => true,
            'filters' => array(
                array('name' => 'StripTags'),
                array('name' => 'StringTrim'),
            ),
            'validators' => array(
                array(
                    'name' => 'StringLength',
                    'options' => array(
                        'encoding' => 'UTF-8',
                        'min' => 1,
                        'max' => 500,
                    ),
                ),
            ),
        );

         array_push($result,$name,$description);
        return $result;

    }
  }

class AttributeFieldSet extends Fieldset implements InputFilterProviderInterface {

    public function __construct($hydrator){
        parent::__construct('attributes');
        $this->setLabel('Item Attribute:');
        $this->setAttributes(array('class'=>'form-horizontal'));

        $this->add(array(
            'name' => 'key',
            'type' => 'Text',
            'options' => array(
                'label' => 'Key',
            )));
        $this->add(array(
            'name' => 'value',
            'type' => 'Text',
            'options' => array(
                'label' => 'Value',
            )));
    }

    /**
     * Should return an array specification compatible with
     * {@link Zend\InputFilter\Factory::createInputFilter()}.
     *
     * @return array
     */
    public function getInputFilterSpecification()
    {
        $result=array();

        $key = array(
            'name' => 'key',
            'required' => true,
            'filters' => array(
                array('name' => 'StripTags'),
                array('name' => 'StringTrim'),
            ),
            'validators' => array(
                array(
                    'name' => 'StringLength',
                    'options' => array(
                        'encoding' => 'UTF-8',
                        'min' => 1,
                        'max' => 100,
                    ),
                ),
            ),
        );

        $value = array(
            'name' => 'value',
            'required' => true,
            'filters' => array(
                array('name' => 'StripTags'),
                array('name' => 'StringTrim'),
            ),
            'validators' => array(
                array(
                    'name' => 'StringLength',
                    'options' => array(
                        'encoding' => 'UTF-8',
                        'min' => 1,
                        'max' => 100,
                    ),
                ),
            ),
        );
        array_push($result,$key,$value);
        return $result;
    }
}

Form View Code:
<?php echo $this->strokerFormPrepare('itemForm');?>


<?php
$form->setAttribute('action', $this->url('item/create'));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

**The code does render properly in the browser so I wont put tons of html here, however the resulting jquery validate rules that are generated in the inline script are of interest - The form inputs for the item have the name item[fieldnamehere]** and the validation code validates fieldnamehere instead of item[fieldnamehere] . **The ItemFieldSet has SetUseAsBaseFieldSet = true, if that makes a difference.

**Generated Javascript**

    //
**HTML Sample**
![image](https://cloud.githubusercontent.com/assets/4597928/7120455/9bc61972-e20d-11e4-9bb1-6eb785f83551.png)

**Comment by rolandhediger** [comment]
Fixed : Problem was assignment of the input filter rules. Implemented InputFilterProviderInterface on each fieldset instead and the jquery validate worked. Sorry to bother you for a zend framework mistake.
