### ISSUE TITLE
Can you make a very simple tutorial ? Sandbox not working !

### ISSUE THREAD

**Issue by invader7** [bramstroker/zf2-form#31]
Hello , im very interested in your module and i want to see it in action. Can  you describe how to use it ? The sandbox example you have is not working it cant fetch or create a FormManager instance.

Thanks

**Comment by bramstroker** [comment]
@invader7 Could you please post the whole stacktrace of the error in a gist/pastebin? I haven't maintained the sandbox and cannot get it running myself. Don´t have much time right now to dive deeper into it, but maybe I can give you some pointers when I see the exact error you got. Did you follow the steps mentioned in the [README](https://github.com/bramstroker/zf2-form#usage)?

**Comment by invader7** [comment]
Thanks for replying , i appreciate it and i understand that you are out of time! Ok leave the sandbox away , i followed the readme till here

"..... (i.e. in your form constructor) it's enough to register the form as an invokable."

After this , i created a folder "Service" under my module "src" folder and added the file MyFormFactory.php inside it with the contents as you mention in your example , i changed the values in order to stick with my module !

Now coming to this part "Now let's add our new factory to the formManager." i can understand that i have to put this code inside my config/autoload/strokerform.global.php file , as i did.

Finally im calling echo $this->strokerFormPrepare('my_form_alias'); and the error i get is 

http://pastebin.com/Nm8UiaD3

thanks !

**Comment by bramstroker** [comment]
The problem is with the factory definition (possibly a naming/namespace/autoload issue). Please post the contents of `config/autoload/strokerform.global.php`

**Comment by invader7** [comment]
<?php
return array(
    'stroker_form' => array(
            'forms' => array(
                'factories' => array(
                    'my_form_alias' => 'Customers\Service\CustomerFactory'
                )
            )
        ,
        'activeRenderers' => array(
            'stroker_form.renderer.jqueryvalidate',
        ),
        'renderer_options' => array(
            'stroker_form.renderer.jqueryvalidate' => array(
                'options_class' => 'StrokerForm\Renderer\JqueryValidate\Options',
                'include_assets' => true,
                'use_twitter_bootstrap' => true,
                /*'validateOptions' => array(
                    'onsubmit' => false,
                    'onkeyup' => false,
                )*/
            )
        )
    ),
);

i installed it , using composer , so stroker module is under vendor folder

**Comment by bramstroker** [comment]
This looks good. You have to doublecheck `Customers\Service\CustomerFactory`. 
- Is this class located in the right directory `module/Customers/src/Customers/Service?
- Is your namespace setup correctly `namespace Customers\Service`?
- Did you enable the module `Customers` in application.config.php?
- Did you setup autoloading correctly? Eighter in you module.php or by using composer autoloading
- Do you have case sensitivity issues with the filename?

**Comment by invader7** [comment]
You are absolute right !! It was a typo in the Service path !  I manage to solve it and now for the first time i can render my form !!!

but when i try echo $this->strokerFormPrepare('my_form_alias'); nothing happens.

I tried to var_dump($this->strokerFormPrepare('my_form_alias')); and i get NULL

We are close , thanks for helping me !

**Comment by bramstroker** [comment]
Glad you got something working ;-)
`strokerFormPrepare()` is not supposed to output something, so NULL is correct here. This method will collect all registered input filters on your form and add them as JS validation rules to the `inlineScript` helper.

The following line is reponsible for outputting the necessary JS code:

    <?php echo $this->inlineScript() ?>

**Comment by invader7** [comment]
Perfect ! It worked ! you made my night !!! Thanks a lot , i appreciate it !!! Problem solved.

**Comment by bramstroker** [comment]
Cool! Have fun with it!
